# -*- coding: utf-8 -*-
"""Workshop1_Namuna_AI.ML.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AVU4ByZVEl7Qu_F8Q2qgPiy8wfYp6khA

QN.1
"""

first_name = input("Please Enter Your First Name: ")
print(first_name)

"""Qn.2

"""

value = int(input("Please Enter a Number: "))

if value < 0:
    print("The number is negative")
elif value == 0:
    print("The number is non-negative")
else:
    print("The number is positive")

"""`

Qn.3.
"""

total = 0

for counter in range(1, 11):
    total = total + counter

print(total)

"""Qn.4."""

first_list = [1, 2, 3, 8]

print("First element:", first_list[0])
print("Last element:", first_list[-1])

for value in first_list:
    print(value)

# append
first_list.append(10)
print("After append:", first_list)

# modify
first_list[2] = 5
print("After modification:", first_list)

# insert
first_list.insert(2, 12)
print("After insert:", first_list)

"""Qn.5.1. Create & Traverse Dictionary"""

zipCode = {'London': 290, 'Leeds': 578, 'Wolverhampton': 911}

for key in zipCode:
    print(key, "=", zipCode[key])

"""Qn.5.2.Keys and Values

"""

print(zipCode.keys())
print(zipCode.values())

"""Qn5.3. Modify and add Values"""

zipCode['London'] = 666
zipCode['Birmingham'] = 111

for key in zipCode:
    print(key, "=", zipCode[key])

"""6: Functions"""

def oddEven(num):
    if num % 2 == 0:
        print("The number is even")
    else:
        print("The number is odd")

num = int(input("Please Enter a Number: "))
oddEven(num)

"""QN. 7
1: Fibonacci Series
"""

a, b = 0, 1

for i in range(10):
    print(a)
    a, b = b, a + b

"""7.2: Factorial of a Number"""

num = int(input("Enter a number: "))
fact = 1

for i in range(1, num + 1):
    fact *= i

print("Factorial is:", fact)

"""7.3: Right Angle Triangle"""

for i in range(1, 6):
    print("*" * i)

"""7.4: Simple Calculator (Functions)"""

def add(a, b):
    return a + b

def subtract(a, b):
    return a - b

def multiply(a, b):
    return a * b

def divide(a, b):
    return a / b

x = int(input("Enter first number: "))
y = int(input("Enter second number: "))

print("Add:", add(x, y))
print("Subtract:", subtract(x, y))
print("Multiply:", multiply(x, y))
print("Divide:", divide(x, y))

"""7.5: Remove First Duplicate from List"""

lst = [1, 2, 3, 2, 4, 5]
seen = []

for item in lst:
    if item not in seen:
        seen.append(item)
    else:
        lst.remove(item)
        break

print(lst)

"""7.6: Extract Keys from Dictionary"""

sample_dict = {
    "name": "Namuna",
    "age": 35,
    "salary": 5000,
    "city": "London"
}

keys = ["name", "salary"]

new_dict = {}

for key in keys:
    new_dict[key] = sample_dict[key]

print(new_dict)

"""7.7: Convert Two Lists into Dictionary"""

list_one = ['one', 'two', 'three']
list_two = [1, 2, 3]

result = {}

for i in range(len(list_one)):
    result[list_one[i]] = list_two[i]

print(result)